## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
! dir

 Volume in drive C has no label.
 Volume Serial Number is 2E6A-E828

 Directory of C:\Users\Scott\Class\World_Weather_Analysis\Vacation_Search

02/13/2022  09:35 AM    <DIR>          .
02/13/2022  09:35 AM    <DIR>          ..
02/11/2022  06:52 PM    <DIR>          .ipynb_checkpoints
02/09/2022  06:38 PM               120 config.py
02/13/2022  09:35 AM            34,714 Vacation_Search.ipynb
02/12/2022  05:42 PM            12,930 WeatherPy_vacation.csv
02/12/2022  02:39 PM           468,536 WeatherPy_vacation_map.PNG
02/12/2022  09:27 AM    <DIR>          Weather_Database
02/11/2022  06:57 PM    <DIR>          __pycache__
               4 File(s)        516,300 bytes
               5 Dir(s)  342,880,239,616 bytes free

In [5]:
# 1. Import the WeatherPy_database.csv file. 
weather_data_df = pd.read_csv("Weather_Database/WeatherPy_Database.csv")
weather_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Current Description
0,0,Busselton,-33.6500,115.3333,70.09,68,13,8.86,AU,2022-02-12 01:16:52,few clouds
1,1,Butaritari,3.0707,172.7902,81.88,78,73,15.43,KI,2022-02-12 01:17:38,light rain
2,2,Cidreira,-30.1811,-50.2056,74.46,83,0,20.31,BR,2022-02-12 01:20:57,clear sky
3,3,Souillac,-20.5167,57.5167,75.58,94,40,3.44,MU,2022-02-12 01:20:57,scattered clouds
4,4,Chumikan,54.7183,135.3150,8.98,92,100,4.41,RU,2022-02-12 01:20:57,light snow

In [6]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip?

ValueError: could not convert string to float:

In [ ]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
weather_data_df = weather_data_df.loc[(weather_data_df["Max Temp"] <= max_temp) & \
                                       (weather_data_df["Max Temp"] >= min_temp)]
weather_data_df.head(10)

In [7]:
# 4a. Determine if there are any empty rows.
weather_data_df.isnull().values.any()
weather_data_df.isnull().sum()

City_ID                0
City                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Country                4
Date                   0
Current Description    0
dtype: int64

In [8]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
weather_data_df = weather_data_df.dropna()

weather_data_df.isnull().values.any()
weather_data_df.isnull().sum()

City_ID                0
City                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Country                0
Date                   0
Current Description    0
dtype: int64

In [9]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = weather_data_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Busselton,AU,70.09,few clouds,-33.6500,115.3333,
1,Butaritari,KI,81.88,light rain,3.0707,172.7902,
2,Cidreira,BR,74.46,clear sky,-30.1811,-50.2056,
3,Souillac,MU,75.58,scattered clouds,-20.5167,57.5167,
4,Chumikan,RU,8.98,light snow,54.7183,135.3150,
5,Punta Arenas,CL,57.31,broken clouds,-53.1500,-70.9167,
6,Eureka,US,65.68,overcast clouds,40.8021,-124.1637,
7,Lata,PT,49.71,overcast clouds,40.1629,-8.3327,
8,Ushuaia,AR,49.66,heavy intensity rain,-54.8000,-68.3000,
9,San Joaquin,US,73.63,clear sky,37.9333,-121.3011,

In [10]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [11]:
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Busselton,AU,70.09,few clouds,-33.6500,115.3333,Observatory Guest House
1,Butaritari,KI,81.88,light rain,3.0707,172.7902,Isles Sunset Lodge
2,Cidreira,BR,74.46,clear sky,-30.1811,-50.2056,Hotel Castelo
3,Souillac,MU,75.58,scattered clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
4,Chumikan,RU,8.98,light snow,54.7183,135.3150,Fortuna
5,Punta Arenas,CL,57.31,broken clouds,-53.1500,-70.9167,Hotel Hain
6,Eureka,US,65.68,overcast clouds,40.8021,-124.1637,Eureka Inn Trademark By Wyndham
7,Lata,PT,49.71,overcast clouds,40.1629,-8.3327,Casa Maquia
8,Ushuaia,AR,49.66,heavy intensity rain,-54.8000,-68.3000,Albatross Hotel
9,San Joaquin,US,73.63,clear sky,37.9333,-121.3011,University Plaza Waterfront Hotel

In [12]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.dropna(inplace = True)
hotel_df.isnull().values.any()
hotel_df.isnull().sum()

City                   0
Country                0
Max Temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [13]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [14]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# SCOTT ADD - From Weather_Database 
# city_current_description = city_weather["weather"][0]["description"]


# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map. 

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)

fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))